# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: abd5a0968c0443267d0015db85aeb567560cd6b1656e99b93c158645d92d88bdad33ca62f99891722c3886df1d53dca1b95c5a05c0fe9a0bc4063ac5926e51ec

test:
  secret_key_base: a2bfa5eff6821d76377065bea1f43addacc4ea53ec19177a7855f3bdf57b6a7404f966729df97bee1639d79e32813e23f049fa69bcfcf3d9e6d060c3bdefb6d6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
